[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="error" type="java.lang.String" --]
[#-- @ftlvariable name="users" type="ru.itmo.wp.model.domain.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.wp.model.domain.User" --]
